w05/d02/recipe-randomiser/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipe
  resources :item
  resources :ingredients
end

w05/d02/recipe-randomiser/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :item
end

w05/d02/recipe-randomiser/app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :recipes  
  has_many :ingredients
end

w05/d02/recipe-randomiser/app/models/recipe.rb
class Recipe < ApplicationRecord
    has_and_belongs_to_many :items
    accepts_nested_attributes_for :items, :allow_destroy => true

end

w05/d02/recipe-randomiser/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

w05/d02/recipe-randomiser/app/controllers/ingredients_controller.rb
class IngredientController < ApplicationController
  def initialize(args)
    
  end
  
  
end

w05/d02/recipe-randomiser/app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /item
  # GET /Item.json
  def index
    @items = Item.all
  end

  # GET /item/1
  # GET /item/1.json
  def show
    set_item
  end

  # GET /item/new
  def new
    @item = Item.new
  end

  # GET /item/1/edit
  def edit
    set_item
  end

  # POST /item
  # POST /Item.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @Item.save
        format.html { redirect_to @item, notice: 'item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @Item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item/1
  # PATCH/PUT /item/1.json
  def update
    # puts params
    puts "This is the params #{params[:items_ids]}" 

    # items_ids.each do |item|

    #   @Item.items << items_ids

    # end
    respond_to do |format|
      if @Item.update(item_params)
        format.html { redirect_to @item, notice: 'item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @Item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item/1
  # DELETE /item/1.json
  def destroy
    @Item.destroy
    respond_to do |format|
      format.html { redirect_to item_url, notice: 'item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :duration, :steps, :url, :video, :image, :item_ids)
    end
end

w05/d02/recipe-randomiser/app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipe
  # GET /recipe.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipe/1
  # GET /recipe/1.json
  def show
    set_recipe
  end

  # GET /recipe/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipe/1/edit
  def edit
    set_recipe
  end

  # POST /recipe
  # POST /recipe.json
  def create
    @recipe = Recipe.new(recipe_params)

    puts items_ids = recipe_params[:items_ids]

    items_ids.each do |item|

      @recipe.items << items_ids

    end

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe/1
  # PATCH/PUT /recipe/1.json
  def update
    # puts params
    puts "This is the params #{params[:item_ids]}" 

    # items_ids.each do |item|

    #   @recipe.items << items_ids

    # end
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe/1
  # DELETE /recipe/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :duration, :steps, :url, :video, :image, item_ids: [])
    end
end

w05/d02/recipe-randomiser/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :title, value: item.title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :duration, value: item.duration %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :description, value: item.description %>
  </div>

  <div class="field">
    <%= form.label :steps %>
    <%= form.text_field :steps, id: :steps, value: item.steps %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :url, value: item.url %>
  </div>

  <div class="field">
    <%= form.label :video_URL %>
    <%= form.text_field :video, id: :video, value: item.video%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :image, value: item.image %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
     <% Item.all.each do |item| %>
     	<p>
     		<%= form.check_box "item[item_ids][]", item.id, form.object.items.include?(item) %>
        <%= item.name %>
     	</p>
        
      <% end %>
  </div>
      <div>
     
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w05/d02/recipe-randomiser/app/views/items/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipe_path %>

w05/d02/recipe-randomiser/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

    <% @recipes.each do |recipe| %>
      <div>
        <h1><%= link_to recipe.title, recipe %></h1>
        <p><%= recipe.description %></p>
        <p><%= recipe.duration %></p>
        <%= image_tag recipe.image %>
        <%= link_to 'Edit', edit_recipe_path(recipe) %>
        <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

w05/d02/recipe-randomiser/app/views/items/new.html.erb
<h1>Editing recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

w05/d02/recipe-randomiser/app/views/items/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= @recipe.duration %></p>
<% if(@recipe.video) %>
		<%= video_tag @recipe.video %>
	<% elsif @recipe.image %>
		<div>
			<%= image_tag @recipe.image %>
		</div>
<% else %>

<% end %>
<table>
	<tr>
		<th>Ingredient List</th>
	</tr>
<% @recipe.items.all.each do |item| %>
		<tr>
			<td><%= "#{item.amount} #{item.name}"  %></td>
		</tr>
<% end %>
	</table>
<p><%= @recipe.description %></p>
<p><%= @recipe.steps %></p>
<a class="edit" href="/recipe/<%= @recipe.id %>/edit">edit</a>

<form class="delete" action="/recipe/<%= @recipe.id %>" method="POST">
<input type="hidden" name="_method" value="DELETE">
<input type="submit" value="Delete">
</form> 

w05/d02/recipe-randomiser/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeRandomiser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w05/d02/recipe-randomiser/app/views/recipe/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :title, value: recipe.title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :duration, value: recipe.duration %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :description, value: recipe.description %>
  </div>

  <div class="field">
    <%= form.label :steps %>
    <%= form.text_field :steps, id: :steps, value: recipe.steps %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :url, value: recipe.url %>
  </div>

  <div class="field">
    <%= form.label :video_URL %>
    <%= form.text_field :video, id: :video, value: recipe.video%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :image, value: recipe.image %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>

     		<%= form.collection_check_boxes :item_ids, Item.all, :id, :name %>

  </div>
      <div>
     
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w05/d02/recipe-randomiser/app/views/recipe/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipe_path %>

w05/d02/recipe-randomiser/app/views/recipe/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

    <% @recipes.each do |recipe| %>
      <div>
        <h1><%= link_to recipe.title, recipe %></h1>
        <p><%= recipe.description %></p>
        <p><%= recipe.duration %></p>
        <%= image_tag recipe.image %>
        <%= link_to 'Edit', edit_recipe_path(recipe) %>
        <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

w05/d02/recipe-randomiser/app/views/recipe/new.html.erb
<h1>Editing recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

w05/d02/recipe-randomiser/app/views/recipe/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= @recipe.duration %></p>
<% if(@recipe.video) %>
		<%= video_tag @recipe.video %>
	<% elsif @recipe.image %>
		<div>
			<%= image_tag @recipe.image %>
		</div>
<% else %>

<% end %>
<table>
	<tr>
		<th>Ingredient List</th>
	</tr>
<% @recipe.items.all.each do |item| %>
		<tr>
			<td><%= "#{item.amount} #{item.name}"  %></td>
		</tr>
<% end %>
	</table>
<p><%= @recipe.description %></p>
<p><%= @recipe.steps %></p>
<a class="edit" href="/recipe/<%= @recipe.id %>/edit">edit</a>

<form class="delete" action="/recipe/<%= @recipe.id %>" method="POST">
<input type="hidden" name="_method" value="DELETE">
<input type="submit" value="Delete">
</form> 