w05/wednesday/diary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'u'
  resources :users do
    resources :posts
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

w05/wednesday/diary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w05/wednesday/diary/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

w05/wednesday/diary/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

w05/wednesday/diary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

w05/wednesday/diary/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_posts
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET users/1/posts
  def index
    @user = current_user.id
    @posts = @user.posts
  end

  # GET users/1/posts/1
  def show
  end

  # GET users/1/posts/new
  def new
    @post = @user.posts.build
  end

  # GET users/1/posts/1/edit
  def edit
  end

  # POST users/1/posts
  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to([@post.user, @post], notice: 'Post was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT users/1/posts/1
  def update
    if @post.update_attributes(post_params)
      redirect_to([@post.user, @post], notice: 'Post was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE users/1/posts/1
  def destroy
    @post.destroy

    redirect_to user_posts_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posts
      @user = User.find(current_user.id)
    end

    def set_post
      @post = @user.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :post)
    end
end

w05/wednesday/diary/app/controllers/users_controller.rb
# class UsersController < ApplicationController

  
  
# end

w05/wednesday/diary/app/helpers/application_helper.rb
module ApplicationHelper
end

w05/wednesday/diary/app/helpers/posts_helper.rb
module PostsHelper
end

w05/wednesday/diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </nav>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

w05/wednesday/diary/app/views/posts/_form.html.erb
<%= form_for([@post.user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

w05/wednesday/diary/app/views/posts/_header.html.erb
<h1>Welcome to your Diary.</h1>

w05/wednesday/diary/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', [@post.user, @post] %> |
<%= link_to 'Back', user_posts_path(@post.user) %>

w05/wednesday/diary/app/views/posts/index.html.erb
<% 
}
  
end%><h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.post %></td>
    <td><%= link_to 'Show', [post.user, post] %></td>
    <td><%= link_to 'Edit', edit_user_post_path(post.user, post) %></td>
    <td><%= link_to 'Destroy', [post.user, post], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_user_post_path(current_user.id) %>

w05/wednesday/diary/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(@post.user) %>

w05/wednesday/diary/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Post:</b>
  <%= @post.post %>
</p>


<%= link_to 'Edit', edit_user_post_path(@post.user, @post) %> |
<%= link_to 'Back', user_posts_path(@post.user) %>